version: '3.4'

services:
  restaurantsimulation.api:
    container_name: restaurantsimulation.api
    image: ${DOCKER_REGISTRY-}restaurantsimulationapi
    build:
      context: .
      dockerfile: RestaurantSimulation.Api/Dockerfile
    ports:
      - "8080:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - Auth0__Domain=dev-88r0xkt1.eu.auth0.com
        - Auth0__Audience=https://restaurantsimulation/api
        - Auth0__ClientId=xCRPlATR4O0ZzZvAvTZ8h1yaJC0RMLGI
        - Auth0__Authority=dev-88r0xkt1.eu.auth0.com
        - UseSwagger=true
    depends_on:
        - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=RestaurantSimulation
    ports:
      - "3306:3306"