name: Build

on:
  push:
    branches: '**'
    paths:
    - 'RestaurantSimulation.Backend/**'               # target all the changes for backend
    - '!RestaurantSimulation.Angular.Frontend/**'     # ignore everything related to frontend

env:
  DOTNET_VERSION: "6.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore 
        run: dotnet restore ./RestaurantSimulation.Backend/RestaurantSimulation.Backend.sln

      - name: Build
        run: dotnet build ./RestaurantSimulation.Backend/RestaurantSimulation.Backend.sln --configuration Release --no-restore

