name: RestaurantSimulation.Backend.CI

on:
  push:
    branches: '**'
    # paths:
    # - 'RestaurantSimulation.Backend/**'               # target all the changes for backend
  pull_request:
    branches: [main]
    paths:
    - 'RestaurantSimulation.Backend/**'               # target all the changes for backend

env:
  DOTNET_VERSION: "6.0.x"

jobs:
  BuildBackend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Dotnet restore 
        run: dotnet restore RestaurantSimulation.Backend/RestaurantSimulation.Backend.sln

      - name: Dotnet build
        run: dotnet build RestaurantSimulation.Backend/RestaurantSimulation.Backend.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test RestaurantSimulation.Backend/tests/RestaurantSimulation.UnitTests/**.csproj --logger "trx;logfilename=UnitTestsResult.trx" --collect:"XPlat Code Coverage"

      - name: Set up MySql Container
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql version: '5.7'
          mysql database: 'RestaurantSimulationTests'
          mysql root password: root-password

      - name: Run integration tests
        run: dotnet test RestaurantSimulation.Backend/tests/RestaurantSimulation.IntegrationTests/**.csproj --logger "trx;logfilename=IntegrationTestsResult.trx" --collect:"XPlat Code Coverage"
      
      - name: The destination for coveragereport
        run: echo "${{ github.workspace }}/coveragereport"

      - name: Merge cobertura reports with ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: 'RestaurantSimulation.Backend/tests/**/coverage.cobertura.xml'
          targetdir: "${{ env.GITHUB_WORKSPACE }}/coveragereport" 
          reporttypes: 'Cobertura'
          toolpath: 'reportgeneratortool'
          verbosity: "Verbose"
      
      - name: Integrate dotnet test reporter
        uses: bibipkins/dotnet-test-reporter@v1.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: 'RestaurantSimulation Test Results'
          results-path: RestaurantSimulation.Backend/tests/**/**/*.trx
          coverage-path: ${{ env.GITHUB_WORKSPACE }}/coveragereport
          coverage-type: 'cobertura'